name: Build assets
on:
  push:
    branches:
      - master

jobs:
  yarn:
    name: Yarn
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache node_modules
      uses: actions/cache@v1
      id: yarn-cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-node-modules-
    - name: Yarn install
      if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Yarn lint
      run: yarn lint
    - name: Install webpack
      run: yarn add webpack --dev
    - name: build webpack
      run: webpack -c webpack.config.js
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Built file
    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: multiple-entity-row.js
